FROM ubuntu:22.04
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        dumb-init \
        jq && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
COPY bundler/* /usr/sbin/
COPY external/board/edgeos/rpi4-root/skeleton/usr/sbin/read-manifest /usr/sbin/
WORKDIR /workdir
ENTRYPOINT ["dumb-init"]