FROM ubuntu:22.04

# Bundler version
ARG BUNDLER_VERSION
ENV BUNDLER_VERSION ${BUNDLER_VERSION}

# Dependencies
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        dumb-init \
        jq \
        curl \
        fakeroot \
        gnupg \
        dirmngr \
        squashfs-tools \
        genext2fs && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Scripts
COPY bundler/create-image /usr/sbin/
COPY bundler/create-upgrade /usr/sbin/
COPY bundler/get-os /usr/sbin/
COPY external/board/edgeos/rpi4-root/skeleton/usr/sbin/read-manifest /usr/sbin/

# Genimage
COPY output/rpi4-boot/host/lib/libconfuse.so.2.1.0 /usr/lib/libconfuse.so.2
COPY output/rpi4-boot/host/bin/genimage /usr/sbin/
COPY buildroot/support/scripts/genimage.sh /usr/sbin/

# Supporting data
COPY bundler/install /data/
COPY bundler/rpi4-genimage.cfg /data/

WORKDIR /workdir
ENTRYPOINT ["dumb-init"]