#!/bin/bash

set -e
set -o pipefail

DOCKER_COMPOSE_FILE="docker-compose.yml"
MANIFEST_FILE="manifest.json"

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 dir" >&2
  exit 1
fi

if ! [ -e "$1" ]; then
  echo "$1 not found" >&2
  exit 1
fi

if ! [ -d "$1" ]; then
  echo "$1 is not a directory" >&2
  exit 1
fi

pushd $1 > /dev/null

echo "[0%] Starting upgrade"
source current-boot > /dev/null 2>&1

echo "[1%] Reading manifest"
source read-manifest $MANIFEST_FILE

echo "[2%] Package $APP_NAME version $APP_VERSION"

echo "[3%] Downloading EdgeOS version $EDGEOS_VERSION"
./get-os $EDGEOS_VERSION > /dev/null 2>&1

echo "[20%] Writing boot partition"
dd if=$(pwd)/boot.vfat of=$NEXT_BOOT_PART > /dev/null 2>&1

echo "[40%] Writing rootfs partition"
dd if=$(pwd)/rootfs.squashfs of=$NEXT_ROOTFS_PART > /dev/null 2>&1

echo "[90%] Creating manifest partition filesystem"
mksquashfs $MANIFEST_FILE $DOCKER_COMPOSE_FILE manifest.squashfs > /dev/null 2>&1

echo "[91%] Writing manifest partition"
dd if=$(pwd)/manifest.squashfs of=$NEXT_MANIFEST_PART > /dev/null 2>&1

popd > /dev/null

echo "[99%] Cleaning up"
rm -rf $TMPDIR

echo "[100%] Rebooting..."
rebootp "0 tryboot"