#!/bin/bash

set -e
set -o pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 dir" >&2
  exit 1
fi

if ! [ -e "$1" ]; then
  echo "$1 not found" >&2
  exit 1
fi

if ! [ -d "$1" ]; then
  echo "$1 is not a directory" >&2
  exit 1
fi

source current-boot > /dev/null

if [ "$TRYBOOT" == "1" ]; then
    echo "An upgrade is already in progress, exiting!" >&2
    exit 1
fi

pushd $1 > /dev/null

source read-manifest manifest.json

if ! [ "$EDGEOS_VERSION" == "$CURRENT_EDGEOS_VERSION" ]; then
    echo "Upgrading EdgeOS from version $CURRENT_EDGEOS_VERSION to $EDGEOS_VERSION"
    ./get-os $EDGEOS_VERSION
else
    echo "EdgeOS version $CURRENT_EDGEOS_VERSION is up to date"
fi

# dd NEXT_BOOT_PART
# dd NEXT_ROOTFS_PART
# mksquashfs $MANIFEST_FILE $DOCKER_COMPOSE_FILE manifest.squashfs > /dev/null 2>&1
# dd NEXT_MANIFEST_PART

popd > /dev/null