#!/bin/bash

# Read manifest
source read-manifest $1

if [ $EDGEOS_VERSION != "local" ] ; then

  # Check if bundler version is same as os version and warn otherwise
  if [ $EDGEOS_VERSION != $BUNDLER_VERSION ]; then
    echo "  Warning: EdgeOS version does not match bundler version"
  fi

else
  
  # Correct version to local version
  export EDGEOS_VERSION=$BUNDLER_VERSION

  # Overwrite version in manifest file
  jq --arg version "$EDGEOS_VERSION" '.edgeos.version = $version' $1 > $1.tmp && mv $1.tmp $1

fi