name: Build

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        configuration: [ "rpi4", "pc" ]

    steps:

    - name: Maximize build space
      uses: AdityaGarg8/remove-unwanted-software@v4.1
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Print the version number
      run: make version

    - name: Install build dependencies
      if: matrix.configuration == 'pc'
      run: |
        sudo apt-get update
        sudo apt-get -y install libelf-dev bc
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

    - name: Download buildroot
      run: make prepare
      
    - name: Build for ${{ matrix.configuration }}
      run: make build-${{ matrix.configuration }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the ${{ matrix.configuration }} Docker image
      run: make push-${{ matrix.configuration }}

    - name: Store the tarbal artifact
      uses: actions/upload-artifact@v4
      with:
        name: edgeos-${{ matrix.configuration }}
        retention-days: 1
        path: output/artifacts/edgeos-${{ matrix.configuration }}.tar.gz

  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs: [ build ]

    steps:
    
    - name: Retrieve artifacts
      uses: actions/download-artifact@v4
      with:
        path: edgeos
        pattern: edgeos-*
        merge-multiple: true

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        artifacts: edgeos/edgeos-*.tar.gz
        omitBody: true