name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: make prepare
      
    - name: Build
      run: make

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: make push

    - name: Store the tarbal artifact
      uses: actions/upload-artifact@v3
      with:
        name: edgeos
        path: output/artifacts/edgeos.tar.gz